# Generated by Django 5.1.4 on 2024-12-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='collaboration/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='research',
            name='pdf_url',
            field=models.FileField(upload_to='research/'),
        ),
    ]
