# Generated by Django 5.1.4 on 2025-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_collaboration_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='multtiple_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='research/'),
        ),
        migrations.AddField(
            model_name='research',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
    ]
