# Generated by Django 5.1.4 on 2025-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_research_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
