# Generated by Django 5.1.4 on 2025-05-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_collaboration_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='multtiple_images',
        ),
        migrations.CreateModel(
            name='collaboration_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collaboration_images/')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.collaboration')),
            ],
        ),
        migrations.CreateModel(
            name='research_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='research_images/')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.research')),
            ],
        ),
    ]
