# Generated by Django 5.1.4 on 2025-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
